name: Publish

on:
  push:
    tags:
      - "v*"

# 権限設定を追加
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Package extension
        run: |
          cd dist
          zip -r ../browser-extension.zip .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: browser-extension.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
